// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoummleAw_OPILvTzKal2AG1BKMssP0ec',
    appId: '1:451409448648:web:bbb675108944870459dffd',
    messagingSenderId: '451409448648',
    projectId: 'registration-d0427',
    authDomain: 'registration-d0427.firebaseapp.com',
    storageBucket: 'registration-d0427.firebasestorage.app',
    measurementId: 'G-E3ZB4XC96S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB3FIsVhkuxgh33iGjrEkm6bswEqpXIl0',
    appId: '1:451409448648:android:60dca88d19fed9dc59dffd',
    messagingSenderId: '451409448648',
    projectId: 'registration-d0427',
    storageBucket: 'registration-d0427.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNdNh7XZszn7UsUSE1llYlIXr_VwAFt8',
    appId: '1:451409448648:ios:30938da2b013eb4059dffd',
    messagingSenderId: '451409448648',
    projectId: 'registration-d0427',
    storageBucket: 'registration-d0427.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPNdNh7XZszn7UsUSE1llYlIXr_VwAFt8',
    appId: '1:451409448648:ios:30938da2b013eb4059dffd',
    messagingSenderId: '451409448648',
    projectId: 'registration-d0427',
    storageBucket: 'registration-d0427.firebasestorage.app',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoummleAw_OPILvTzKal2AG1BKMssP0ec',
    appId: '1:451409448648:web:bedc6e2cf705139b59dffd',
    messagingSenderId: '451409448648',
    projectId: 'registration-d0427',
    authDomain: 'registration-d0427.firebaseapp.com',
    storageBucket: 'registration-d0427.firebasestorage.app',
    measurementId: 'G-E8MQ1EENLP',
  );
}
